# Generated by Django 4.0.1 on 2022-01-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='blog_view',
            new_name='views',
        ),
    ]
